spring:
  datasource:
    url: jdbc:mysql://localhost:3306/perfman
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Test123456

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6000
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
  
  mail:
    host: localhost
    port: 1025
    username: 
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

grpc:
  client:
    idService:
      address: 'static://localhost:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    tokenService:
      address: 'static://localhost:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.code4faster.perfmanauthservice.model

security:
  jwt:
    secret: perfmansecretkey
    expiration: 3600000
  # user:
  #   name: admin
  #   password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
