spring:
  datasource:
    url: jdbc:mysql://localhost:3306/perfman
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Test123456

security:
  jwt:
    secret: perfmansecretkey
    expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
