spring:
  datasource:
    url: jdbc:mysql://localhost:3306/perfman
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Test123456

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6000
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5

security:
  jwt:
    secret: perfmansecretkey
    expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

id-generator:
  worker-id: 1
  datacenter-id: 1
